name: B18_G40 Deployment Pipeline

on:
  push:
    branches:
      - "feature/code"
  
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

# Steps are below that will be run as part of the workflow

jobs:
  Terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Environment/Dev

    steps:
      - name: checkout plan
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Azure Login
        uses: Azure/login@v2.3.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform formatting
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan


