name: Terraform CSV Automation

on:

  push:

    branches:
      - main

    paths:
      - 'Environment/Dev/Resource_input.csv'


permissions:
  contents: write


jobs:

  generate-tfvars:

    runs-on: windows-latest

    defaults:
      run:
        working-directory: Environment/Dev


    steps:

      # -----------------------------
      # Checkout
      # -----------------------------

      - name: Checkout Repository

        uses: actions/checkout@v4


      # -----------------------------
      # Generate terraform.tfvars
      # -----------------------------

      - name: Generate terraform.tfvars

        shell: powershell

        run: |

          Set-ExecutionPolicy `
            -Scope Process `
            -ExecutionPolicy Bypass

          .\Generate-TerraformTfvars.ps1


      # -----------------------------
      # Terraform Format
      # -----------------------------

      - name: Terraform Format

        shell: powershell

        run: |

          terraform fmt -recursive


      # -----------------------------
      # Terraform Init
      # -----------------------------

      - name: Terraform Init

        shell: powershell

        run: |

          terraform init -backend=false


      # -----------------------------
      # Terraform Validate
      # -----------------------------

      - name: Terraform Validate

        shell: powershell

        run: |

          terraform validate


      # -----------------------------
      # Commit generated tfvars
      # -----------------------------

      - name: Commit terraform.tfvars

        shell: powershell

        run: |

          git config user.name `
            "github-actions[bot]"

          git config user.email `
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add terraform.tfvars

          if (git diff --cached --quiet) {

              Write-Host `
                "No terraform.tfvars changes."

              exit 0
          }

          git commit `
            -m "Auto generate terraform.tfvars"

          git push
